# Promise.all

## 参数为 Promise 实例组成的数组

`Promise.all` 方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。

`Promise.all` 方法接受一个数组作为参数，每一个元素都应该是 Promise 实例，如果不是，会使用 `Promise.resolve` 包装成 Promise 实例。

## 输出结果

```js
const p = Promise.all([p1, p2, p3])
  .then(result => console.log(result))
  .catch(e => console.log(e));
```

p 的状态有两种：

- fulfilled：当所有的 Promise 实例（p2, p2, p3）都为 fulfilled 状态，则p的状态为 fulfilled，会执行then 函数的第一个回调，result 为三个结果组成的数组；

```js
const p1 = new Promise((resolve, reject) => {
  resolve('hello');
})

const p2 = new Promise((resolve, reject) => {
  resolve('world');
})

let p = Promise.all([p1, p2])
.then(result => console.log(result))
.catch(e => console.log(e));
// result: ["hello", "world"]
```

- rejected：只要有一个 Promise 实例状态为 rejected，则 p 的状态为 rejected，会执行 catch 回调。就算其他的 Promise 实例为 resolve 状态，也不会执行 then 函数的第一个回调，无法 resolve 的输出结果。

```js
const p1 = new Promise((resolve, reject) => {
  resolve('hello');
})

const p2 = new Promise((resolve, reject) => {
  throw new Error('出错了')
})

let p = Promise.all([p1, p2])
.then(result => console.log(result))
.catch(e => console.log(e));
// Error: 出错了
```

## Promise.all 的实现

```js
function promiseAll(promises) {
  return new Promise((resolve, reject) => {
    if (!Array.isArray(promises)) {
      return reject(new TypeError('arguments must be an array'));
    }
    let resolvedCounter = 0;
    let promiseNum = promises.length;
    let result = [];

    promises.forEach(promise => {
      Promise.resolve(promise).then(function resolvedHandler(value) {
        resolvedCounter++;
        result.push(value);
        if (promiseNum === resolvedCounter) {
          return resolve(result);
        }
      }, function rejectedHandler(reason) {
        return reject(reason);
      });
    });
  });
}

// 试验：
let p1 = Promise.resolve(1);
let p2 = Promise.resolve(2);

promiseAll([p1, p2]).then(result => console.log(result));
// [1, 2]
```

# 实战例题

## 题目1

> 10 个 Ajax 同时发起请求，全部返回展示结果，并且至多允许三次失败，说出设计思路

不能使用 promise.all，可以通过记录失败的次数来报错，以下为伪代码

```js
// promise 方法
let errcount = 0;
let p = new Promise((resolve, reject) => {
  if(success) {
    resolve(res);
  } else {
    errcount++;
    if(errcount > 3) {
      reject(error);
    } else {
      resolve(error)
    }
  }
});

let list = [1,1,1,1,1,1,1,1,1,1].map(() => {
  return p;
});

Promise.all(list).then(v => {
  console.log(v);
}).catch(error => {
  console.log(error);
})

// 非promise方法
let errcount = 0;
let successcount = 0;
let data = [];

ajax(url, (res) => {
  if(success) {
    successcount++;
    data.push(res);
  } else {
    errcount++;
    if(errcount > 3) {
      throw new Error('失败三次了');
    }
  }
});
// 然后再并发是个ajax请求
```


